"""add owner relationship on monitor

Revision ID: 6d0ffb88c40c
Revises: e6811293a447
Create Date: 2026-05-12 14:45:05.793501

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '6d0ffb88c40c'
down_revision: Union[str, Sequence[str], None] = 'e6811293a447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
