"""add oauth fields and model relations

Revision ID: e6811293a447
Revises: 7b3f421e9630
Create Date: 2026-05-12 14:33:55.372733

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6811293a447'
down_revision: Union[str, Sequence[str], None] = '7b3f421e9630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_monitors_owner_id'), 'monitors', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'monitors', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('google_sub', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), server_default='local', nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_sub')
    op.drop_constraint(None, 'monitors', type_='foreignkey')
    op.drop_index(op.f('ix_monitors_owner_id'), table_name='monitors')
    op.drop_column('monitors', 'owner_id')
    # ### end Alembic commands ###
